const mongoose = require("mongoose");

const billSchema = new mongoose.Schema({
    customer: { type: mongoose.Schema.Types.ObjectId, ref: "customer" },
    order_id: { type: mongoose.Schema.Types.ObjectId, ref: "order", required: true },
    order_no: { type: Number, required: true },
    financial_year: { type: String, required: true },
    quarterly: { type: String, enum: ["Q1", "Q2", "Q3", "Q4"] },
    half_yearly: { type: String, enum: ["H1", "H2"] },
    month: String,
    bill_no: Number,
    invoice_prifix: {
      type: String,
      default: "INV",
    },
    invoice_no: String,
    date: { type: Date, default: Date.now() },
    company_details: {
      company_name: String,
      gst_no: String, 
      country:String,
      state: String,
      district: String,
      city: String,
      area: String,
      pincode: String,
      address_line1: String,
      address_line2: String,
      landline_no_1: String,
      landline_no_2: String,
      email: String,
      mobile_no: String,
      website: String,
      logo: String,
      pan_no:String,
      invoice_notes: String,
      invoice_title: String,
      invoice_text: [String],
    },
    delivery_address: {
      firstname: String,
      lastname: String,
      city: String,
      state: String,
      landmark: String,
      address_line_1: String,
      address_line_2: String,
      pincode: Number,
      mobile_no: Number,
      alternate_no: Number,
    },
    products: [
        {
          product: { type: mongoose.Schema.Types.ObjectId, ref: "products" },
          productspec_id: { type: mongoose.Schema.Types.ObjectId },
          product_name: String,
          sku: String,
          product_image:[String],
          qrcode: String,
          kg: { type: Number },
          mrp: { type: Number },
          sp: { type: Number },
          tax: { type: Number },
          tax_persentage: { type: Number },
          //delivery_charge: { type: Number },
          qty: { type: Number },
          total: { type: Number },
        },
    ],
    tax: Number,
    total: Number,
    no_of_items: Number,
    cancel: { type: Boolean, default: false },
    done_by: String,
}, {
    timestamps: true,
    versionKey: false,
});
module.exports = mongoose.model("bill", billSchema);
